# Generated by Django 4.1 on 2024-10-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('prise', models.FloatField(help_text='Можно использовать нецелые числа.', verbose_name='Цена в руб.')),
                ('image', models.ImageField(upload_to='img/%Y/%m/%d/', verbose_name='Цена')),
                ('adding_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('category', models.ManyToManyField(related_name='goods', to='main.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
