# Generated by Django 4.1 on 2024-10-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='goods', to='main.category', verbose_name='Категории'),
        ),
    ]
